# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 08589511ad3052d9aad935619d295626c8c2de7d9968ec36585aafb3296d500f03f77be2df7c0118c0eb9649a9de45311dcefaac31bf4ffe94f3ca90b1f5483f

test:
  secret_key_base: e0cb40f977900952dc4f16e4cf7f0c8cf5a5997a437e4e24b569094e582b79003459dee40a7e3777634ecfa12aa19e05b04f3e9ef247170769c6810afed9f218

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
